/* Part 4 semantic invariants. Every row is checked; violations must be zero. */
WITH checks AS (
    SELECT 'user_cold_start_consistency' AS check_name, COUNT(*) AS rows_checked,
           COUNT(*) FILTER (WHERE (user_cold_start = 1 AND (user_prior_txn_count <> 0 OR user_seconds_since_prev_txn IS NOT NULL)) OR (user_prior_txn_count = 0 AND user_cold_start <> 1)) AS violations,
           'cold start implies zero prior count and NULL recency' AS notes
    FROM analytics.behavioral_features_v1
    UNION ALL SELECT 'card_cold_start_consistency', COUNT(*), COUNT(*) FILTER (WHERE (card_cold_start = 1 AND (card_prior_txn_count <> 0 OR card_seconds_since_prev_txn IS NOT NULL)) OR (card_prior_txn_count = 0 AND card_cold_start <> 1)), 'cold start implies zero prior count and NULL recency' FROM analytics.behavioral_features_v1
    UNION ALL SELECT 'merchant_cold_start_consistency', COUNT(*), COUNT(*) FILTER (WHERE (merchant_cold_start = 1 AND (merchant_prior_txn_count <> 0 OR merchant_seconds_since_prev_txn IS NOT NULL)) OR (merchant_prior_txn_count = 0 AND merchant_cold_start <> 1)), 'cold start implies zero prior count and NULL recency' FROM analytics.behavioral_features_v1
    UNION ALL SELECT 'user_merchant_new_consistency', COUNT(*), COUNT(*) FILTER (WHERE user_merchant_is_new = 1 AND (user_merchant_prior_txn_count <> 0 OR user_merchant_seconds_since_prev_txn IS NOT NULL)), 'new relationship implies zero prior count and NULL recency' FROM analytics.behavioral_features_v1
    UNION ALL SELECT 'card_merchant_new_consistency', COUNT(*), COUNT(*) FILTER (WHERE card_merchant_is_new = 1 AND (card_merchant_prior_txn_count <> 0 OR card_merchant_seconds_since_prev_txn IS NOT NULL)), 'new relationship implies zero prior count and NULL recency' FROM analytics.behavioral_features_v1
    UNION ALL SELECT 'relationship_count_hierarchy', COUNT(*), COUNT(*) FILTER (WHERE user_merchant_prior_txn_count > user_prior_txn_count OR card_merchant_prior_txn_count > card_prior_txn_count OR user_mcc_prior_txn_count > user_prior_txn_count OR card_mcc_prior_txn_count > card_prior_txn_count OR user_channel_prior_txn_count > user_prior_txn_count OR card_channel_prior_txn_count > card_prior_txn_count), 'relationship history cannot exceed entity history' FROM analytics.behavioral_features_v1
    UNION ALL SELECT 'non_negative_recency', COUNT(*), COUNT(*) FILTER (WHERE (user_seconds_since_prev_txn < 0 OR card_seconds_since_prev_txn < 0 OR merchant_seconds_since_prev_txn < 0 OR user_merchant_seconds_since_prev_txn < 0 OR card_merchant_seconds_since_prev_txn < 0)), 'recency is NULL or non-negative' FROM analytics.behavioral_features_v1
    UNION ALL SELECT 'current_positive_amount_semantics', COUNT(*), COUNT(*) FILTER (WHERE (current_positive_amount AND amount <= 0) OR ((NOT current_positive_amount) AND amount > 0)), 'positive flag agrees with source amount' FROM analytics.behavioral_features_v1
    UNION ALL SELECT 'amount_ratio_semantics', COUNT(*), COUNT(*) FILTER (WHERE current_positive_amount_vs_user_mean IS NOT NULL AND (amount <= 0 OR user_prior_positive_amount_mean IS NULL OR user_prior_positive_amount_mean <= 0) OR current_positive_amount_vs_card_mean IS NOT NULL AND (amount <= 0 OR card_prior_positive_amount_mean IS NULL OR card_prior_positive_amount_mean <= 0)), 'ratios require a positive current amount and positive prior mean' FROM analytics.behavioral_features_v1
    UNION ALL SELECT 'amount_z_semantics', COUNT(*), COUNT(*) FILTER (WHERE current_positive_amount_user_z IS NOT NULL AND (amount <= 0 OR user_prior_positive_amount_std IS NULL OR user_prior_positive_amount_std <= 0) OR current_positive_amount_card_z IS NOT NULL AND (amount <= 0 OR card_prior_positive_amount_std IS NULL OR card_prior_positive_amount_std <= 0)), 'z-scores require positive current amount and positive prior standard deviation' FROM analytics.behavioral_features_v1
    UNION ALL SELECT 'state_missing_not_new', COUNT(*), COUNT(*) FILTER (WHERE state_missing_flag = 1 AND merchant_state IS NOT NULL), 'missing state is an availability flag, not a familiarity flag' FROM analytics.behavioral_features_v1
)
SELECT check_name, rows_checked, violations, CASE WHEN violations = 0 THEN 'PASS' ELSE 'FAIL' END AS status, notes
FROM checks
ORDER BY check_name;

