/* Part 3 — geography risk. Scope: DEVELOPMENT_DISCOVERY. Missing state/city becomes <UNKNOWN>. */
CREATE OR REPLACE TABLE analytics.part3_state_risk AS
WITH baseline AS (SELECT COUNT(*) AS txns, SUM(fraud_label) AS fraud_txns, SUM(amount) FILTER (WHERE fraud_label=1) AS fraud_amount FROM analytics.part3_development), segments AS (
  SELECT COALESCE(NULLIF(TRIM(merchant_state), ''), '<UNKNOWN>') AS segment_value, COUNT(*) AS transactions, SUM(fraud_label) AS fraud_transactions, SUM(amount) AS total_amount, SUM(amount) FILTER (WHERE fraud_label=1) AS fraud_amount FROM analytics.part3_development GROUP BY 1)
SELECT 'DEVELOPMENT_DISCOVERY' AS analysis_scope, 'state' AS segment_type, segment_value, transactions, transactions*1.0/baseline.txns AS transaction_share, fraud_transactions, fraud_transactions*1.0/NULLIF(transactions,0) AS fraud_rate, (fraud_transactions*1.0/NULLIF(transactions,0))/NULLIF(baseline.fraud_txns*1.0/baseline.txns,0) AS fraud_lift, fraud_transactions*1.0/NULLIF(baseline.fraud_txns,0) AS fraud_capture_share, segments.total_amount, segments.fraud_amount, segments.fraud_amount*1.0/NULLIF(segments.total_amount,0) AS fraud_amount_share, segments.fraud_amount*1.0/NULLIF(baseline.fraud_amount,0) AS fraud_amount_capture_share, CASE WHEN transactions>=1000 THEN 'SUFFICIENT' ELSE 'LOW_SUPPORT' END AS support_status FROM segments CROSS JOIN baseline;

CREATE OR REPLACE TABLE analytics.part3_merchant_city_risk AS
WITH baseline AS (SELECT COUNT(*) AS txns, SUM(fraud_label) AS fraud_txns, SUM(amount) FILTER (WHERE fraud_label=1) AS fraud_amount FROM analytics.part3_development), segments AS (
  SELECT COALESCE(NULLIF(TRIM(merchant_city), ''), '<UNKNOWN>') AS segment_value, COUNT(*) AS transactions, SUM(fraud_label) AS fraud_transactions, SUM(amount) AS total_amount, SUM(amount) FILTER (WHERE fraud_label=1) AS fraud_amount FROM analytics.part3_development GROUP BY 1)
SELECT 'DEVELOPMENT_DISCOVERY' AS analysis_scope, 'merchant_city' AS segment_type, segment_value, transactions, transactions*1.0/baseline.txns AS transaction_share, fraud_transactions, fraud_transactions*1.0/NULLIF(transactions,0) AS fraud_rate, (fraud_transactions*1.0/NULLIF(transactions,0))/NULLIF(baseline.fraud_txns*1.0/baseline.txns,0) AS fraud_lift, fraud_transactions*1.0/NULLIF(baseline.fraud_txns,0) AS fraud_capture_share, segments.total_amount, segments.fraud_amount, segments.fraud_amount*1.0/NULLIF(segments.total_amount,0) AS fraud_amount_share, segments.fraud_amount*1.0/NULLIF(baseline.fraud_amount,0) AS fraud_amount_capture_share, CASE WHEN transactions>=1000 THEN 'SUFFICIENT' ELSE 'LOW_SUPPORT' END AS support_status FROM segments CROSS JOIN baseline;
