/* Part 3 — user/card concentration. Scope: DEVELOPMENT_DISCOVERY. Entity values are not exported to public reports. */
CREATE OR REPLACE TABLE analytics.part3_user_entity AS SELECT CAST(user_id AS VARCHAR) AS entity_value, COUNT(*) AS transactions, SUM(fraud_label) AS fraud_transactions, SUM(amount) AS total_amount, SUM(amount) FILTER (WHERE fraud_label=1) AS fraud_amount FROM analytics.part3_development GROUP BY 1;
CREATE OR REPLACE TABLE analytics.part3_card_entity AS SELECT card_key AS entity_value, COUNT(*) AS transactions, SUM(fraud_label) AS fraud_transactions, SUM(amount) AS total_amount, SUM(amount) FILTER (WHERE fraud_label=1) AS fraud_amount FROM analytics.part3_development GROUP BY 1;

CREATE OR REPLACE TABLE analytics.part3_user_concentration AS
WITH r AS (SELECT *, ROW_NUMBER() OVER (ORDER BY fraud_transactions DESC, entity_value) AS fraud_rank, COUNT(*) OVER () AS total_entities, SUM(fraud_transactions) OVER () AS all_fraud FROM analytics.part3_user_entity)
SELECT 'DEVELOPMENT_DISCOVERY' AS analysis_scope, 'USER' AS entity_type, MAX(total_entities)::BIGINT AS total_entities, COUNT(*) FILTER (WHERE fraud_transactions>=1)::BIGINT AS fraud_affected_entities, COUNT(*) FILTER (WHERE fraud_transactions>=2)::BIGINT AS repeat_fraud_entities, MAX(all_fraud)::BIGINT AS entity_fraud_transactions, SUM(fraud_transactions) FILTER (WHERE fraud_rank<=10)*1.0/NULLIF(MAX(all_fraud),0) AS top_10_fraud_share, SUM(fraud_transactions) FILTER (WHERE fraud_rank<=100)*1.0/NULLIF(MAX(all_fraud),0) AS top_100_fraud_share, SUM(fraud_transactions) FILTER (WHERE fraud_rank<=CEIL(total_entities*.01))*1.0/NULLIF(MAX(all_fraud),0) AS top_1pct_fraud_share, SUM(fraud_transactions) FILTER (WHERE fraud_rank<=CEIL(total_entities*.05))*1.0/NULLIF(MAX(all_fraud),0) AS top_5pct_fraud_share, SUM(POWER(fraud_transactions*1.0/NULLIF(all_fraud,0),2)) AS hhi_fraud_count FROM r;

CREATE OR REPLACE TABLE analytics.part3_card_concentration AS
WITH r AS (SELECT *, ROW_NUMBER() OVER (ORDER BY fraud_transactions DESC, entity_value) AS fraud_rank, COUNT(*) OVER () AS total_entities, SUM(fraud_transactions) OVER () AS all_fraud FROM analytics.part3_card_entity)
SELECT 'DEVELOPMENT_DISCOVERY' AS analysis_scope, 'CARD' AS entity_type, MAX(total_entities)::BIGINT AS total_entities, COUNT(*) FILTER (WHERE fraud_transactions>=1)::BIGINT AS fraud_affected_entities, COUNT(*) FILTER (WHERE fraud_transactions>=2)::BIGINT AS repeat_fraud_entities, MAX(all_fraud)::BIGINT AS entity_fraud_transactions, SUM(fraud_transactions) FILTER (WHERE fraud_rank<=10)*1.0/NULLIF(MAX(all_fraud),0) AS top_10_fraud_share, SUM(fraud_transactions) FILTER (WHERE fraud_rank<=100)*1.0/NULLIF(MAX(all_fraud),0) AS top_100_fraud_share, SUM(fraud_transactions) FILTER (WHERE fraud_rank<=CEIL(total_entities*.01))*1.0/NULLIF(MAX(all_fraud),0) AS top_1pct_fraud_share, SUM(fraud_transactions) FILTER (WHERE fraud_rank<=CEIL(total_entities*.05))*1.0/NULLIF(MAX(all_fraud),0) AS top_5pct_fraud_share, SUM(POWER(fraud_transactions*1.0/NULLIF(all_fraud,0),2)) AS hhi_fraud_count FROM r;
